package com.springboot.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class Employee {


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.tenant_id
	 * @mbg.generated
	 */
	private Long tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.store_id
	 * @mbg.generated
	 */
	private Long storeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.empl_code
	 * @mbg.generated
	 */
	private String emplCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.realname
	 * @mbg.generated
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.head_img
	 * @mbg.generated
	 */
	private String headImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.mobile
	 * @mbg.generated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.telephone
	 * @mbg.generated
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.birthday
	 * @mbg.generated
	 */
	private LocalDate birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.gender
	 * @mbg.generated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.zipcode
	 * @mbg.generated
	 */
	private String zipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.country
	 * @mbg.generated
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.province
	 * @mbg.generated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.district
	 * @mbg.generated
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.id_card
	 * @mbg.generated
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.hiredate
	 * @mbg.generated
	 */
	private LocalDate hiredate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.leavedate
	 * @mbg.generated
	 */
	private LocalDate leavedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.end_date
	 * @mbg.generated
	 */
	private LocalDate endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.remarks
	 * @mbg.generated
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.order_no
	 * @mbg.generated
	 */
	private Integer orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.empl_type
	 * @mbg.generated
	 */
	private Integer emplType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.user_type
	 * @mbg.generated
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.user_account
	 * @mbg.generated
	 */
	private String userAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.user_name
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.user_pass
	 * @mbg.generated
	 */
	private String userPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.term_pass
	 * @mbg.generated
	 */
	private String termPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.discount_give
	 * @mbg.generated
	 */
	private BigDecimal discountGive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.discount
	 * @mbg.generated
	 */
	private BigDecimal discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.present
	 * @mbg.generated
	 */
	private BigDecimal present;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.is_disc_scheme
	 * @mbg.generated
	 */
	private Integer isDiscScheme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.dig_limit_type
	 * @mbg.generated
	 */
	private Integer digLimitType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.pre_limit_type
	 * @mbg.generated
	 */
	private Integer preLimitType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.is_display
	 * @mbg.generated
	 */
	private Integer isDisplay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.is_pos_user
	 * @mbg.generated
	 */
	private Integer isPosUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.is_cloud_user
	 * @mbg.generated
	 */
	private Integer isCloudUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.create_user
	 * @mbg.generated
	 */
	private Long createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.create_time
	 * @mbg.generated
	 */
	private LocalDateTime createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.update_user
	 * @mbg.generated
	 */
	private Long updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.update_time
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.delete_flag
	 * @mbg.generated
	 */
	private Integer deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.post_id
	 * @mbg.generated
	 */
	private Long postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.crm_empl_id
	 * @mbg.generated
	 */
	private Long crmEmplId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.pass_flag
	 * @mbg.generated
	 */
	private Integer passFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.kb_empl_code
	 * @mbg.generated
	 */
	private String kbEmplCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.salt
	 * @mbg.generated
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column acl_employee.encry_name
	 * @mbg.generated
	 */
	private String encryName;
}
